### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by AlexandreFaltot** [BatchLabs/Batch-iOS-firebase-dispatcher#3]
It would be nice to add Swift Package Manager integration. Have you considered using it in the future ?

**Comment by abarisain** [comment]
Thanks for the feedback, we will consider this for future releases!

**Comment by wsantos24s** [comment]
Do you have any updates on spm integration ?
This is our last dependency that does not support spm...

**Comment by wsantos24s** [comment]
Ok thank you!

**Comment by abarisain** [comment]
Hi,

Support for SPM has been released

Thanks for your feedback!
